In [1]:
#1. Import the numpy package under the name np
import numpy as np

In [2]:
#2. Print the numpy version and the configuration
print(np.__version__)

1.24.3


In [7]:
#3. Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#4. How to find the memory size of any array

# Create an example array
my_array = np.zeros((3, 4), dtype=np.float64)
print(my_array)

# Find the memory size in bytes
memory_size = my_array.nbytes

print(f"Memory size of the array: {memory_size} bytes")


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Memory size of the array: 96 bytes


In [10]:
#5. How to get the documentation of the numpy add function from the command line?
#activate your environment and activate python in command line.
#then run help(np.add). 
#Here in vs code, we already activate our kernel and we have imported numpy
help(np.add)


Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [11]:
#6. Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
#7. Create a vector with values ranging from 10 to 49
vec = np.arange(10,50,1)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
#8. Reverse a vector (first element becomes last)
original_vector = np.array([1, 2, 3, 4, 5])

reversed_vector = original_vector[::-1]

print(reversed_vector)

#trying to reverse #7
print(vec[::-1]) 

[5 4 3 2 1]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [23]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3_3 = np.array([[0, 1, 2],
                       [3, 4, 5],
                       [6, 7, 8]])
print(matrix_3_3)

#alternatively
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])

nonzero_indices = np.nonzero(arr)

print(nonzero_indices)

(array([0, 1, 4]),)


In [33]:
#11. Create a 3x3 identity matrix
id_mat_eye = np.eye(3)
print(id_mat_eye)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
#12. Create a 3x3x3 array with random values
random_mat = np.random.rand(3,3,3)
random_mat

array([[[0.40868916, 0.27315508, 0.02156654],
        [0.18227914, 0.32856822, 0.47348579],
        [0.98189079, 0.04118374, 0.21291362]],

       [[0.36937218, 0.91145429, 0.76496059],
        [0.82302614, 0.43606957, 0.00349918],
        [0.50505768, 0.03805277, 0.13052213]],

       [[0.4466751 , 0.14254803, 0.10948844],
        [0.37337189, 0.04640682, 0.40327872],
        [0.62705992, 0.91301147, 0.39035351]]])

In [43]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
array_10_10 = np.random.rand(10,10)
print(array_10_10)
min_value = np.min(array_10_10)
max_value = np.max(array_10_10)
print(min_value)
print(max_value)

[[0.54288975 0.06082503 0.56024522 0.90217105 0.64933676 0.1038325
  0.13065881 0.35245601 0.97511738 0.38351802]
 [0.58361094 0.70692217 0.24567269 0.18948215 0.03573551 0.74762983
  0.67349608 0.34283669 0.84745766 0.17378097]
 [0.70316582 0.98472423 0.08967998 0.68668289 0.25842438 0.24282001
  0.3587404  0.58180352 0.3002354  0.45807954]
 [0.56270391 0.82931454 0.78280025 0.41748039 0.77437667 0.53100839
  0.69101079 0.83904484 0.03545213 0.45299916]
 [0.90662151 0.78214734 0.86501695 0.66150266 0.91636487 0.66396069
  0.90484322 0.60598413 0.62768255 0.89786218]
 [0.84955051 0.80990965 0.83321356 0.07966633 0.11503739 0.80872539
  0.55217599 0.73149342 0.87739176 0.25185919]
 [0.54204083 0.12062515 0.65222734 0.33978416 0.00922623 0.03754318
  0.07516187 0.45867761 0.98487434 0.59630443]
 [0.41022258 0.43305241 0.75470896 0.60999104 0.72834107 0.86429639
  0.21868316 0.31284743 0.45457236 0.04213338]
 [0.07901265 0.78701411 0.371325   0.9872461  0.24868144 0.25439846
  0.20370581 

In [45]:
#14.  Create a random vector of size 30 and find the mean value
rand_vec = np.random.rand(30)
print(rand_vec)
mean_val = np.mean(rand_vec)
print(mean_val)

[0.26198762 0.16198917 0.63109114 0.99851813 0.68923709 0.98272464
 0.67059643 0.59886204 0.61838556 0.07555584 0.3961562  0.44888809
 0.26349231 0.25888526 0.08790828 0.57338913 0.81812231 0.48853223
 0.57389623 0.99747921 0.3587949  0.69041193 0.36106588 0.23175987
 0.42467168 0.50503343 0.93865289 0.58948535 0.32910304 0.83617762]
0.5286951165932684


In [55]:
#15. Create a 2d array with 1 on the border and 0 inside 
array2d = np.ones((5,5)) #2d 5x5 array
array2d[1:-1,1:-1] = 0
print(array2d)
#alternatively
array_with_border = np.pad(np.zeros((3, 3)), pad_width=1, constant_values=1)

print(array_with_border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
#16. How to add a border (filled with 0's) around an existing array?

# Example existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Add a border of 0's around the existing array
array_with_border = np.pad(existing_array, pad_width=1, constant_values=0)

print("Existing Array:")
print(existing_array)

print("\nArray with Border:")
print(array_with_border)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [58]:
#17. What is the result of the following expression?
np.nan


nan

In [59]:
0 * np.nan

nan

In [60]:
np.nan == np.nan

False

In [61]:
np.inf > np.nan

False

In [62]:
np.nan - np.nan

nan

In [63]:
np.nan in set([np.nan])

True

In [64]:
0.3 == 3 * 0.1

False

In [70]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


matrix = np.diag([1, 2, 3, 4], k=-1) #k=-1 means below diag, 1 means above, 0 means on the diag

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [67]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np

# Create an 8x8 matrix with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)

# Fill the even rows and columns with 1
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [71]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

shape = (6, 7, 8)
desired_index = 100

indices = np.unravel_index(desired_index, shape)

print("Indices (x, y, z):", indices)


Indices (x, y, z): (1, 5, 4)


In [72]:
#21.  Create a checkerboard 8x8 matrix using the tile function

# Create a 2x2 checkerboard
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))

print(checkerboard_tile)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [73]:
#22. Normalize a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix using Min-Max scaling
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

Original Matrix:
[[0.90707944 0.08582725 0.29041737 0.45977501 0.59113438]
 [0.52270774 0.55677832 0.17807635 0.56964559 0.09190004]
 [0.51890171 0.17176123 0.9676952  0.37028063 0.00690894]
 [0.99931506 0.38447087 0.5203297  0.25641003 0.42409907]
 [0.17288549 0.23671945 0.23864719 0.93397967 0.22432953]]

Normalized Matrix:
[[0.90705859 0.07952219 0.28567783 0.45633139 0.58869592]
 [0.51974569 0.55407697 0.17247718 0.5670427  0.08564144]
 [0.51591053 0.16611374 0.96813818 0.36615221 0.        ]
 [1.         0.38045102 0.51734944 0.25141027 0.42038246]
 [0.16724659 0.23156902 0.23351151 0.93416466 0.21908428]]


In [74]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

# Define the custom dtype for RGBA color
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

# Create an array with the custom dtype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=rgba_dtype)

print(color_array)




[(255,   0, 0, 255) (  0, 255, 0, 128)]


In [77]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np

# Create a 5x3 matrix
matrix_a = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix_b = np.random.rand(3, 2)

# Multiply the matrices using numpy.dot
result_dot = np.dot(matrix_a, matrix_b)

# Alternatively, you can use the @ operator
result_operator = matrix_a @ matrix_b

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)
print("\nResult (using numpy.dot):")
print(result_dot)
print("\nResult (using @ operator):")
print(result_operator)


Matrix A:
[[0.74304971 0.21510548 0.04270026]
 [0.15573462 0.44194241 0.26096165]
 [0.68486512 0.65365932 0.59706251]
 [0.32567343 0.93314441 0.34176153]
 [0.10699759 0.64904795 0.78539097]]

Matrix B:
[[0.55825764 0.69851476]
 [0.66583055 0.05830172]
 [0.35772629 0.90839215]]

Result (using numpy.dot):
[[0.57331199 0.5703608 ]
 [0.47455165 0.37160446]
 [1.03114249 1.05886475]
 [0.92538283 0.59234512]
 [0.77284318 0.82602301]]

Result (using @ operator):
[[0.57331199 0.5703608 ]
 [0.47455165 0.37160446]
 [1.03114249 1.05886475]
 [0.92538283 0.59234512]
 [0.77284318 0.82602301]]


In [76]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.


# Create a 1D array
arr = np.array([1, 5, 4, 9, 2, 7, 6, 3, 8])

# Negate elements between 3 and 8 in place
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)


[ 1 -5 -4  9  2 -7 -6  3  8]


In [83]:
#26. What is the output of the following script? 
# Author: Jake VanderPlas

print(sum(range(5),-1))


10


In [82]:
from numpy import *
print(sum(range(5),-1)) #in numpy, the second argument in sum means the axis on which the sum should be done. -1 means the last axis

10


In [ ]:


#27. Consider an integer vector Z, which of these expressions are legal?
#1. `Z**Z`: This is legal. It raises each element of `Z` to the power of itself.

#2. `2 << Z >> 2`: This is legal. It performs a bitwise left shift (`<<`) by `Z` positions, followed by a bitwise right shift (`>>`) by 2 positions.

#3. `Z <- Z`: This is legal. It performs an element-wise comparison, checking if each element in `Z` is less than its negation.

#4. `1j*Z`: This is legal. It multiplies each element of `Z` by the imaginary unit `1j`.

#5. `Z/1/1`: This is legal. It divides each element of `Z` by 1, and then divides the result by 1 again. This is equivalent to `Z`.

#6. `Z<Z>Z`: This is not legal. The expression `Z < Z` produces a boolean array, and you cannot compare a boolean array with `Z` using `<`. This will raise a `ValueError`.



In [85]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)


/var/folders/4k/mygtm1_96r7g77fdsqmbmb4m0000gn/T/ipykernel_6567/3867454011.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [86]:
np.array(0) // np.array(0)


/var/folders/4k/mygtm1_96r7g77fdsqmbmb4m0000gn/T/ipykernel_6567/474058805.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [87]:

np.array([np.nan]).astype(int).astype(float)

/var/folders/4k/mygtm1_96r7g77fdsqmbmb4m0000gn/T/ipykernel_6567/3343435198.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

In [88]:
#29. How to round away from zero a float array ?
# Create a float array
float_array = np.array([-3.7, -1.5, 0.3, 1.5, 2.7])

# Round away from zero using numpy.ceil and numpy.floor
rounded_up = np.ceil(float_array)
rounded_down = np.floor(float_array)

print("Original array:", float_array)
print("Rounded up:", rounded_up)
print("Rounded down:", rounded_down)






Original array: [-3.7 -1.5  0.3  1.5  2.7]
Rounded up: [-3. -1.  1.  2.  3.]
Rounded down: [-4. -2.  0.  1.  2.]


In [89]:
#30. How to find common values between two arrays? 

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)


Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]
Common values: [3 4 5]


In [ ]:
#31. How to ignore all numpy warnings (not recommended)
# Ignore all NumPy warnings (not recommended)
np.seterr(all='ignore')

# Your code here

# Reset to the default warning settings if needed
np.seterr(all='warn')


In [91]:
#32. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/4k/mygtm1_96r7g77fdsqmbmb4m0000gn/T/ipykernel_6567/991187553.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [92]:
#33. How to get the dates of yesterday, today and tomorrow?
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-09
Today: 2024-02-10
Tomorrow: 2024-02-11


In [93]:
#34. How to get all the dates corresponding to the month of July 2016?
import pandas as pd

# Create a date range for the month of July 2016
start_date = '2016-07-01'
end_date = '2016-07-31'
date_range = pd.date_range(start_date, end_date)

print(date_range)


DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


In [95]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
# Assuming A and B are NumPy arrays

# Assuming A and B are NumPy arrays
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

# In-place computation of ((A+B)*(-A/2))
A += B
A *= -A / 2

print(A)


[-12.5 -24.5 -40.5]


In [96]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods

# Generate a random array of positive numbers
random_array = np.random.rand(4) * 10  

# Method 1: Using numpy.floor
integer_part_floor = np.floor(random_array)

# Method 2: Using numpy.ceil
integer_part_ceil = np.ceil(random_array)

# Method 3: Using numpy.trunc
integer_part_trunc = np.trunc(random_array)

# Method 4: Using numpy.astype(int)
integer_part_cast = random_array.astype(int)


print("Original array:", random_array)
print("Integer part (using floor):", integer_part_floor)
print("Integer part (using ceil):", integer_part_ceil)
print("Integer part (using trunc):", integer_part_trunc)
print("Integer part (using astype):", integer_part_cast)


Original array: [7.42862153 3.85883038 1.0810567  8.41479091]
Integer part (using floor): [7. 3. 1. 8.]
Integer part (using ceil): [8. 4. 2. 9.]
Integer part (using trunc): [7. 3. 1. 8.]
Integer part (using astype): [7 3 1 8]


In [101]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
# Step 1: Generate an array with values from 0 to 4
row_values = np.arange(5)

# Step 2: Create a 5x5 matrix by replicating the array along the rows
matrix = np.tile(row_values, (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [102]:
#38. Consider a generator function that generates 10 integers and use it to build an array
# Generator function to yield 10 integers
def generate_integers():
    for i in range(10):
        yield i

# Create an array from the generator
generated_array = np.array(list(generate_integers()))

print(generated_array)

[0 1 2 3 4 5 6 7 8 9]


In [110]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [113]:
#40. Create a random vector of size 10 and sort it 
rand_vec = np.random.rand(10)
print(rand_vec)
print(np.sort(rand_vec))

[0.00326139 0.90423164 0.51362341 0.96581604 0.18803237 0.1307981
 0.61287484 0.37809346 0.87310071 0.40501269]
[0.00326139 0.1307981  0.18803237 0.37809346 0.40501269 0.51362341
 0.61287484 0.87310071 0.90423164 0.96581604]


In [114]:
#41. How to sum a small array faster than np.sum?

import timeit

# Create a small array
small_array = np.array([1, 2, 3, 4, 5])

# Using np.sum
start_time = timeit.default_timer()
sum_np = np.sum(small_array)
elapsed_time_np = timeit.default_timer() - start_time

# Using built-in Python sum
start_time = timeit.default_timer()
sum_builtin = sum(small_array)
elapsed_time_builtin = timeit.default_timer() - start_time

# Using np.add.reduce
start_time = timeit.default_timer()
sum_reduce = np.add.reduce(small_array)
elapsed_time_reduce = timeit.default_timer() - start_time

print("Using np.sum:", sum_np, "Elapsed Time:", elapsed_time_np)
print("Using built-in sum:", sum_builtin, "Elapsed Time:", elapsed_time_builtin)
print("Using np.add.reduce:", sum_reduce, "Elapsed Time:", elapsed_time_reduce)


Using np.sum: 15 Elapsed Time: 0.001065708000169252
Using built-in sum: 15 Elapsed Time: 3.4374999813735485e-05
Using np.add.reduce: 15 Elapsed Time: 2.7582998882280663e-05


In [115]:
#42. Consider two random array A and B, check if they are equal 
# Create two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are arrays A and B equal?", are_equal)

Array A: [0.78879145 0.27513284 0.42103764 0.56550831 0.99087574]
Array B: [0.58913648 0.91595472 0.12016335 0.57839264 0.36250184]
Are arrays A and B equal? False


In [116]:
#43. Make an array immutable (read-only) 

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Make the array read-only
my_array.flags.writeable = False

# Try to modify the array (will raise an error)
try:
    my_array[0] = 10
except ValueError as e:
    print(f"Error: {e}")

# Check if the array is read-only
print("Is the array read-only?", not my_array.flags.writeable)


Error: assignment destination is read-only
Is the array read-only? True


In [117]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

# Create a random 10x2 matrix representing cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert to polar coordinates
r = np.hypot(x, y)
theta = np.arctan2(y, x)

# Display the results
print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print("Radius (r):", r)
print("Angle (theta):", theta)


Cartesian Coordinates:
[[0.74176015 0.10683892]
 [0.24228438 0.12534535]
 [0.52652076 0.97338316]
 [0.75384224 0.33074747]
 [0.8439104  0.91553589]
 [0.44460861 0.42438362]
 [0.89447958 0.24043677]
 [0.13587044 0.86300382]
 [0.00916133 0.50932299]
 [0.91783224 0.92069601]]

Polar Coordinates:
Radius (r): [0.74941488 0.27278779 1.10666115 0.82320836 1.24514687 0.6146367
 0.92623083 0.873634   0.50940538 1.30003737]
Angle (theta): [0.1430505  0.47742954 1.07495236 0.41345824 0.82608481 0.76212829
 0.26259372 1.41463916 1.55281099 0.7869558 ]


In [121]:
#45. Create random vector of size 10 and replace the maximum value by 0

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original random vector:", random_vector)


Original random vector: [0.21194684 0.00356447 0.54634191 0.         0.07957941 0.55700057
 0.01872104 0.69915353 0.11370928 0.608772  ]


In [124]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

# Create a structured array with x and y coordinates
grid = np.zeros((5, 5), dtype=[('x', float), ('y', float)])

# Fill in x and y coordinates covering [0, 1]x[0, 1]
grid['x'], grid['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

print(grid)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [125]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

# Given arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1.0 / (X[:, np.newaxis] - Y)

print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [126]:
#48. Print the minimum and maximum representable value for each numpy scalar type 
import numpy as np

# Print the minimum and maximum representable values for each numpy scalar type
dtypes = [np.int8, np.int16, np.int32, np.int64,
          np.uint8, np.uint16, np.uint32, np.uint64,
          np.float16, np.float32, np.float64]

for dtype in dtypes:
    info = np.finfo(dtype) if np.issubdtype(dtype, np.floating) else np.iinfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")


int8: Min = -128, Max = 127
int16: Min = -32768, Max = 32767
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807
uint8: Min = 0, Max = 255
uint16: Min = 0, Max = 65535
uint32: Min = 0, Max = 4294967295
uint64: Min = 0, Max = 18446744073709551615
float16: Min = -65504.0, Max = 65504.0
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308


In [127]:
#49. How to print all the values of an array?

# Create a NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print all values using the print function
print(my_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [128]:
#alternatively
# Print each element individually
for row in my_array:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9


In [129]:
#50. How to find the closest value (to a given scalar) in a vector?
import numpy as np

# Create a NumPy vector
vector = np.array([1.2, 2.5, 3.8, 4.1, 5.3])

# Given scalar
scalar = 3.0

# Find the index of the closest value
index_closest = np.argmin(np.abs(vector - scalar))

# Get the closest value
closest_value = vector[index_closest]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value:", closest_value)


Vector: [1.2 2.5 3.8 4.1 5.3]
Scalar: 3.0
Closest value: 2.5
